### ISSUE TITLE
Converter not working

### ISSUE THREAD

**Issue by skoch9** [luxonis/tools#69] opened 2023-12-14 20:06 UTC
Currently, the online converter for yolo<x> models under [https://tools.luxonis.com/](https://tools.luxonis.com/) doesn't seem to work anymore. When I'm uploading different pretrained yolo weights (yolov5n.pt, yolov6n.pt, yolov6s.pt, ...) it's starting the conversion but doesn't finish it (it says `Preparing zip file...`). At some point I then get the error:
```
An error occurred
Error: timeout of 1500000ms exceeded

Please try again or reach out to us on our [Discuss](https://discuss.luxonis.com/) or create an issue on
```
I tried to instead run the converter locally as described in this repo, but the docker-compose bringup also has issues (different yolo versions are not found in the docker service containers) and accessing the webclient under `0.0.0.0` gives a 'BAD GATEWAY' nginx error. 

Could you look into this, because currently it's impossible to convert any custom (or OTS) models with this tool?

**Comment by HonzaCuhel** [comment] 2023-12-14 21:12
Hi @skoch9,

thank you for reporting. I will look into it.

Best
Jan

**Comment by HonzaCuhel** [comment] 2023-12-14 23:47
I tried converting several models, and the conversions were successful for all the models. Some inner components weren't working briefly, but now the app is back to 100% functional.

**Comment by skoch9** [comment] 2023-12-15 00:52
Thanks for looking into this so fast. It's still not working for me in Chrome with for example these two models:

**Comment by HonzaCuhel** [comment] 2023-12-15 08:33
Hmm, that's interesting. I've tried to convert both of your models, and it worked for me. Besides the input image shapes, what other parameters do you set? Could you please try to refresh your browser (maybe empty the browser's cache for the tools) or try a different browser?

Best,
Jan

**Comment by HonzaCuhel** [comment] 2023-12-20 14:16
Hi @skoch9,

I'd like to ask you, is it working for you now or still not?

Best
Jan

**Comment by skoch9** [comment] 2023-12-20 17:06
Thanks Jan for getting back again. It's strange, it was working perfectly fine the last days but often fails again today. Disabling the cache seems to help, but it still fails sometimes. I'd be interested in getting it running locally, is it possible that the documentation for this is outdated because it fails for me as described above.

Best,
Anna

**Comment by HonzaCuhel** [comment] 2023-12-20 21:53
I see. We think that the occasional outages could be caused by high traffic, we are currently looking into that. I apologize for the inconvenience.

Regarding the local setup, have you cloned the corresponding repositories of various YOLO versions (such as ultralytics, and YoloV6, and so on)? I noticed that it's not described in the steps, I'll update it. And again I apologize for the inconvenience.

Best
Jan

**Comment by skoch9** [comment] 2023-12-21 23:59
Yes, it looks like some resource issues. It just occurred again (in case you need some timestamp for debugging, this was between 0.30am and 1am CET). 

Thanks for the explanation around the local setup, I will try this out.

**Comment by HonzaCuhel** [comment] 2023-12-22 10:46
Thank you for the information! I'll look into it. I want to note that if our blobconverter causes the issue, it will fail even with the local setup. I apologize, we are working on solving it as we speak.

Best,
Jan

**Comment by HonzaCuhel** [comment] 2023-12-27 09:45
Hi @skoch9,

I apologize for the delay in my response. We have updated the README.md to include the steps to clone the repository and all its modules. If you have cloned the repository without the submodules, please use this command:
`git submodule update --init --recursive` to pull the remaining modules. Otherwise, use `git clone --recursive https://github.com/luxonis/tools.git` to clone the tools repository with all its modules.

Kind regards,
Jan

**Comment by HonzaCuhel** [comment] 2024-01-07 21:30
Hi @skoch9,

is everything now for you? Can I close this issue?

Best,
Jan

**Comment by skoch9** [comment] 2024-01-08 19:43
Hi Jan, 
thanks a lot for your help. I could get the local conversion working now so this is great (except for v7 models but they are not so relevant anyways). The online converter is still working sometimes and failing often, but I don't need to use it anymore.

Thanks again for looking into this,
Anna

**Closed** 2024-01-08 19:44 UTC
