### ISSUE TITLE
tools.luxonis.com - Converting failure

### ISSUE THREAD

**Issue by sckle** [luxonis/tools#61] opened 2023-08-10 15:30 UTC
The pretrained file (from colab.research.google.com)
[best.zip](https://github.com/luxonis/tools/files/12314530/best.zip)

Error message:
![image](https://github.com/luxonis/tools/assets/20793780/e6d8829b-9d14-4ee8-9b68-4c1c8aa59db0)

Please assist!

**Comment by tersekmatija** [comment] 2023-08-10 16:34
CC @HonzaCuhel .

@sckle In the meantime, can you link the Colab file that you used?

**Comment by HonzaCuhel** [comment] 2023-08-10 18:08
Hey @sckle, 

thank you for reporting the issue, I'll look into it.

Best,
Jan

**Comment by sckle** [comment] 2023-08-11 19:13
@HonzaCuhel  Any news?

**Comment by HonzaCuhel** [comment] 2023-08-11 22:03
Hi @sckle,

the issue is outdated version of `ultralytics` repository. I locally updated the repository and I was able to convert your model. So in the meantime while we deploy the change, I am sending you the converted [model](https://drive.google.com/file/d/1tfVknfyqXhYr4AO_5mWBgo84F37MmPan/view?usp=sharing).

Best,
Jan

**Comment by sckle** [comment] 2023-08-12 08:36
Thank, @HonzaCuhel

**Comment by HonzaCuhel** [comment] 2023-08-15 19:05
@sckle I've deployed the fix today in the morning, so you should be able to convert it yourself now.

**Comment by bherbruck** [comment] 2023-09-27 19:47
@HonzaCuhel you might need to update the `yolov5` code to use `ultralytics` as well, the new `yolov5` models from ultralytics hub all export in the new format

**Comment by HonzaCuhel** [comment] 2023-09-29 15:23
Hi @bherbruck,

I apologize for the delay in my response. Thank you for reporting. I'll look into it.

Best,
Jan

**Comment by alfonsodou** [comment] 2023-10-24 15:58
Is there any other way to transform the new yolo5 format generated by hub ultralytics while working on updating the yolov5 code? Thanks

**Comment by HonzaCuhel** [comment] 2023-10-25 05:24
Hi @alfonsodou,

in the meantime you should be able to use the `YoloV8` conversion option to convert the latest yolov5 code. Let me know please  if it works for you. I am working on the solution at the moment.

Best,
Jan

**Comment by alfonsodou** [comment] 2023-10-26 07:17
Hi @HonzaCuhel,
it's working fine.
thank you.

**Comment by woerstcase** [comment] 2023-10-26 08:46
Hello Thread,

I face an similar issue

I have an Yolov8n Costum Model but the converter can't open the model:
Input Information:
Name: images, Shape: [1, 3, 640, 640]

Output Information:
Name: output0, Shape: [1, 6, 8400]

I tried multiple shapes(with"," without "," only 640, only 640 640), but the error is: "Error while loading the model"

is there something I oversee

**Comment by HonzaCuhel** [comment] 2023-10-26 10:38
Hi @woerstcase,

could you please share with me your model so that I look into it?

Best
Jan

**Comment by woerstcase** [comment] 2023-10-26 10:41
@HonzaCuhel can I send you it via dm?

**Comment by woerstcase** [comment] 2023-10-26 11:22
> Hi @woerstcase,
> 
> could you please share with me your model so that I look into it?
> 
> Best Jan


[yolov8n.pt.zip](https://github.com/luxonis/tools/files/13176667/yolov8n.pt.zip)

**Comment by woerstcase** [comment] 2023-10-26 11:42
Is it possible to send via dm?

**Comment by HonzaCuhel** [comment] 2023-10-26 11:46
@woerstcase Yeah, sure. You can send it to me via email for example. My email is [jan.cuhel@luxonis.com](https://mail.google.com/mail/u/0/).

**Comment by HonzaCuhel** [comment] 2023-10-26 13:10
@woerstcase Thank you! I'll look into it and will get back to you!

**Comment by HonzaCuhel** [comment] 2023-11-06 08:17
Hi @alfonsodou, @woerstcase,

during the weekend I deployed newest version of the Tools. The update includes better automatic version detector, so now the new yolov5 models (such as `yolov5nu`, `yolov5n6u`,  and so on)  generated by Ultralytics hub will be converted using YoloV8 option. The update also includes better loading of weights. Please note that the reason why we decided not to change the YoloV5 export options is to support older YoloV5 models, which are not compatible with the newest Ultralytics code.

Best
Jan

**Comment by woerstcase** [comment] 2023-11-06 08:27
Hello Jan,

I will test it and let you know.

Thnaks you

Best regards 
David

**Comment by woerstcase** [comment] 2023-11-06 16:01
Tested and works for me👍Am 06.11.2023 um 09:17 schrieb Honza Čuhel ***@***.***>:﻿
Hi @alfonsodou, @woerstcase,
during the weekend I deployed newest version of the Tools. The update includes better automatic version detector, so now the new yolov5 models (such as yolov5nu, yolov5n6u,  and so on)  generated by Ultralytics hub will be converted using YoloV8 option. The update also includes better loading of weights. Please note that the reason why we decided not to change the YoloV5 export options is to support older YoloV5 models, which are not compatible with the newest Ultralytics code.
Best
Jan

**Comment by alfonsodou** [comment] 2023-11-06 19:54
It's ok! Thank you!

**Comment by HonzaCuhel** [comment] 2023-11-07 10:49
Glad to hear that! Closing the issue now, if anything happens, feel free to reopen it.

**Closed by HonzaCuhel** 2023-11-07 10:49 UTC
